### ISSUE TITLE
[discussion] Dependency Analyzer for Java Projects

### ISSUE THREAD

**Issue by apoorvaanand1998** [chaoss/grimoirelab-graal#23]
[JDeps](https://docs.oracle.com/javase/8/docs/technotes/tools/unix/jdeps.html) is a class/package dependency analyzer for Java. It is present in Oracle Java/OpenJDK's bin folder. [This](https://blog.codefx.org/tools/jdeps-tutorial-analyze-java-project-dependencies/) is a relevant tutorial. 

Here are a few issues I am facing while trying to integrate JDeps as an analyzer:
- Given a JAR file, the output I am getting is extremely large. Here's an [example](https://pastebin.com/MPjvwjce)
- How would I use the git backend to get the relevant JAR files for analysis from github?

Sorry for any mistakes, I am not experienced with Java.

**Comment by valeriocos** [comment]
Sorry for the late reply @apoorvaanand1998 and thank you for reporting your feedback. I'll check how to use the git backend to get the relevant JAR files.

Thanks!
