### ISSUE TITLE
[graal] Checkout log an issue in case of large repositories

### ISSUE THREAD

**Issue by inishchith** [chaoss/grimoirelab-graal#33]
**Issue Scenario:** I found this out when I was working on the integration task of Graal with ELK (https://github.com/inishchith/gsoc-graal/issues/4). which causes the [checkout log](https://github.com/chaoss/grimoirelab-graal/blob/master/graal/graal.py#L325) (for the number of commits):
```
Git repository <repo-path> checked out!
```
This wouldn't be a `good to have` in case of repositories of a large number of commits causing a console log for eg. [image attached below on the first run]

![Screenshot 2019-06-04 at 6 45 07 PM](https://user-images.githubusercontent.com/20226361/58881975-e85e0d00-86f8-11e9-8e99-f9f67d685ee8.png)

@valeriocos @jgbarah I was thinking if we could remove the logger for the checkout purpose (a small change but would lead to better log). Would like to have your thoughts :)

Thanks!

**Comment by valeriocos** [comment]
Thank you for reporting this potential issue @inishchith . Maybe we could change the log level to `debug` (this could be applied to most messages except the one in `graal.fetch_items`. What do you think ?

**Comment by inishchith** [comment]
@valeriocos Thanks for the quick response!
Yes. That would be better indeed. 
I'd propose a fix for this in some time :)

**Comment by valeriocos** [comment]
great! thanks @inishchith
