### ISSUE TITLE
[analyzer] Fix results for deleted files

### ISSUE THREAD

**Issue by inishchith** [chaoss/grimoirelab-graal#35]
A file, when deleted in a `commit`, is incorrectly handled. [REF](https://github.com/chaoss/grimoirelab-graal/blob/master/graal/backends/core/cocom.py#L139) and would lead to
- Duplicate files ( in case the file path is changed )
- Loosing out information related to a file.

The issue persists in `CoCom` and `CoLic` backend as the analysis performed in both the cases is at file level

>issue triggered in discussion of https://github.com/inishchith/gsoc-graal/issues/6

@valeriocos I've currently worked on a fix for `CoCom` backend. If you agree, i can open a PR and we can review the changes and then move ahead with working on resolving the same issue for `CoLic`.

Thanks :)

**Comment by valeriocos** [comment]
Yes, sure @inishchith , thanks

**Comment by valeriocos** [comment]
Fixed with https://github.com/chaoss/grimoirelab-graal/commit/3382cb4aeeb45631e6fe035eedebbd9a21257b30
