### ISSUE TITLE
[cocom] Evaluating results with repository level analysis

### ISSUE THREAD

**Issue by inishchith** [chaoss/grimoirelab-graal#36]
- Evaluating an option of `repository_level` analysis for the ease of visualization 

> issue triggered in discussion of inishchith/gsoc-graal#6

**Comment by valeriocos** [comment]
Would this option imply to execute the analysis at repository level for each commit? If so, the analysis for large repositories may be problematic.

**Comment by inishchith** [comment]
@valeriocos Yes, had the thought and thanks for pointing it out!. 
I've had a look at [Lizard's Usage](https://github.com/terryyin/lizard#usage) and would evaluate and update you how it goes.

**Comment by inishchith** [comment]
@valeriocos 

I've tried to implement the repository level analysis. Below is the comparison.

| Repository   | Number of Commits |  *File Level           | Repository Level  |
| :-------------: | :---------: |:-------------: | :-----:|
| [coala/coala](https://github.com/coala/coala) | 4458 | 58.89 min | 59.92 min |
| [chaoss/grimoirelab-perceval]()| 1387 | 24.83 min | 26.63 min |
| [chaoss/grimoirelab-graal]()   | 169 | 1.82 min  | 1.86 min |

_* represents current in-place method_

I feel this would be good-to-have option in `Graal` and as I've mentioned in https://github.com/inishchith/gsoc-graal/issues/6#issuecomment-501297676, would make it easier to visualize the data in Kibana. I'm yet to discover an edge case in the implementation. If you agree, i could draft the rough idea ( in a PR ) and we can then review the idea.
Let me know what you think.

**Comment by valeriocos** [comment]
yes sure @inishchith , feel free to submit a PR and we can discuss there, thanks!
