### ISSUE TITLE
[cocom] Redundant log on every file-open operation

### ISSUE THREAD

**Issue by inishchith** [chaoss/grimoirelab-graal#47]
- A log appears very frequently during the execution of ELK and Graal via the new connector.
- It's related to `read` file-type operation related to lizard library.

(Not sure why it doesn't show up while executing the lizard-analyzer via the command line interface)

**LOG**
```sh
/usr/local/lib/python3.6/site-packages/lizard_ext/auto_open.py:26: DeprecationWarning: 'U' mode is deprecated
  return open(*args, **kwargs)
```
(ref. [lizard_ext:line](https://github.com/terryyin/lizard/blob/master/lizard_ext/auto_open.py#L9))

- In order to reproduce this issue, execute the CoCom-backend task via the micro-mordred with the corresponding connector under elk.

/cc @valeriocos

**Comment by valeriocos** [comment]
Thanks @inishchith for reporting this issue! I'll check it out!

**Comment by valeriocos** [comment]
The following PR should fix this issue: https://github.com/chaoss/grimoirelab-graal/pull/52

**Comment by inishchith** [comment]
@valeriocos If you agree we can close this in reference to #52

**Comment by valeriocos** [comment]
sure!
