### ISSUE TITLE
[QUESTION] Does Grall work with Kibiter?

### ISSUE THREAD

**Issue by kelson42** [chaoss/grimoirelab-graal#51]
Do we can somehow get Grall output ingested by Kibiter?  I would like to improve https://hub.docker.com/r/grimoirelab/full to benefit of Graal computed numbers.

**Comment by valeriocos** [comment]
Hi @kelson42, sorry for the late reply and thank you for the interest in Graal. There is an ongoing Google Summer of Code project  to integrate Graal with Grimoirelab toolchain. You can find more details at:
- https://github.com/inishchith/gsoc
- https://github.com/chaoss/grimoirelab-elk/pull/672
- https://github.com/chaoss/grimoirelab-sirmordred/pull/320
- https://grimoirelab-incubator.biterg.io (some dashboards about license and code complexity data)

Don't hesitate to ping @inishchith or myself for further details/improvements/feature requests

**Comment by kelson42** [comment]
@valeriocos Thank you. This looks promising. Really eager to use this in our future GrimoirLab instance for https://github.com/openzim/ and https://github.com/kiwix/. Hopefully it will work out for us with a reasonable amount of work.
@florentk Could you please have a look to the pointers given so we can know if this is viable for us?
