### ISSUE TITLE
update license information

### ISSUE THREAD

**Issue by valeriocos** [chaoss/grimoirelab-graal#6]
Most files in Graal come with a old copyright date (e.g., `# Copyright (C) 2015-2018 Bitergia` -> https://github.com/chaoss/grimoirelab-graal/blob/master/tests/base_analyzer.py#L4). The goal of this issue is to check each file included in Graal and update the copyright dates where needed.

**Comment by inishchith** [comment]
@valeriocos I'd like to work on this issue 😄

**Comment by valeriocos** [comment]
perfect! thanks!
