### ISSUE TITLE
Add support for Lua & Golang

### ISSUE THREAD

**Issue by inishchith** [chaoss/grimoirelab-graal#8]
`Lizard` has added support for : 
- `Golang` : in release [v1.15.3](https://pypi.org/project/lizard/1.15.3/)
- `Lua` : in release [v1.16.1](https://pypi.org/project/lizard/1.16.1/)

We can add support for the above languages in `graal`.

@valeriocos Please let me know what you think, I'll be interested in working on this issue 😅

**Comment by valeriocos** [comment]
That's perfect! I would start by checking the setup.py and requirements.txt

Thank you!

**Comment by inishchith** [comment]
@valeriocos Thanks. I'll start working on it. 👍
