### ISSUE TITLE
[cocom] Error: Complex regular subexpression recursion limit exceeded

### ISSUE THREAD

**Issue by svdo** [chaoss/grimoirelab-graal#85]
When I try to analyse the repository https://github.com/philips-software/cogito, I see the following error message on the console (multiple times): 

```
Complex regular subexpression recursion limit (32766) exceeded at /usr/bin/cloc line 7327
```

I don't see any information about this in my log file. I'm running a self-built `full-3p` from master 0.2.36 (c612e657fdd99e00c9389d0021612784eb1ec122).

Does this mean anything to you?

**Comment by svdo** [comment]
@valeriocos maybe? Or should I put this in grimoirelab-preceval?

**Comment by svdo** [comment]
Hmm never mind. This is something going wrong in `cloc` itself. Moreover, it appears to be only a warning, when I run `cloc` manually I still get the output table.

**Comment by svdo** [comment]
Created an issue about this over here: https://github.com/AlDanial/cloc/issues/454.

**Comment by valeriocos** [comment]
Thank you for opening the issue upstream!

**Comment by svdo** [comment]
@valeriocos It does raise the question though whether `cloc` should be called with the `--strip-str-comments`, which is needed to make the warning disappear even after the fix is deployed. Quoting from the `cloc` README:

>  Doing so, however, has drawbacks: cloc will run more slowly and the output of `--strip-comments` will contain strings that no longer match the input source.

Given that it is just a warning, I guess I would not add the option without verifying the impact in both of those two aspects... It might be something you should be able to configure somehow maybe?
