### ISSUE TITLE
[cocom] [colic] Problem with enrichment?

### ISSUE THREAD

**Issue by svdo** [chaoss/grimoirelab-graal#86]
I am running five different projects through Grimoirelab now, including cocom and colic analysis. I'm using my self-built version of `grimoirelab/full-3p` v0.2.36.

Somehow only two of the projects show up on the dashboards. When investigating this, I found something strange in the enriched index. For example, I run this query (to filter out the bulk of the entries):

```
GET cocom_chaoss_enrich/_search
{
  "query": {
    "bool": {
      "must_not": [
        {
          "match": {
            "origin": "https://github.com/philips-software/cogito"
          }
        }
      ]
    }
  }
}
```

This gives me hits that have "_id" and "file_path" from one project, and (in the same hit) a different "project" key and "origin". In other words, it seems information from multiple projects gets mistakenly combined into the index. Unless of course I'm misinterpreting this, which could very well be...

**Comment by valeriocos** [comment]
Hi @svdo, sorry for the late reply.

The error was due to the fact that the param `git-path` in your configuration file was set `/tmp/git-cocom`. This caused to clone the repos in the same folder (mixing their info). With the fix at #87, each repo has now its own folder and you don't need to set the `git-path` param.

**Comment by svdo** [comment]
Great find, @valeriocos! I hope it gets merged soon, so that I can verify that it indeed fixes the issue for me. Thanks again!!!

**Comment by valeriocos** [comment]
You're welcome @svdo. The fix will be available in the next release (0.2.38)

**Comment by valeriocos** [comment]
@svdo the release is out, please check if the error is gone on your side. Thanks

**Comment by svdo** [comment]
I'm trying to build the full-3p image from 0.2.38, but I get an error:

```bash
> docker run -v $(pwd)/build:/build -t grimoirelab/fossology-factory
Starting container: 6bbddef6ee53
Getting FOSSology source package...
dget: retrieving https://mentors.debian.net/debian/pool/main/f/fossology/fossology_3.6.0-1.dsc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
dget: curl fossology_3.6.0-1.dsc https://mentors.debian.net/debian/pool/main/f/fossology/fossology_3.6.0-1.dsc failed
Building packages...
/entrypoint.sh: line 9: cd: fossology-3.6.0: No such file or directory
debuild: fatal error at line 679:
cannot find readable debian/changelog anywhere!
Are you in the source code tree?
If FOSSology packages were built, look for them where you mounted /build
```

In other words: 404 on https://mentors.debian.net/debian/pool/main/f/fossology/fossology_3.6.0-1.dsc...

**Comment by valeriocos** [comment]
The package at https://mentors.debian.net/package/fossology has been removed. I'm checking how to fix this.

**Comment by valeriocos** [comment]
sorry @svdo for the late reply! I found a link that could be used to solve this problem: http://mirrors.kernel.org/fossology/releases/3.0.0/debian/7.0/. I'm going to open an issue to track it
